### ISSUE TITLE
Enable searching through all resources

### ISSUE THREAD

**Issue by 0xmichalis** [eug48/fhir#3]
According to the FHIR search spec, seaching all resources that match a provided parameter is possible:

> All resource types: GET [base]?parameter(s) (parameters common to all types). If the _type parameter is included, all other search parameters SHALL be common to all provided types. If _type is not included, all parameters SHALL be common to all resource types.

https://www.hl7.org/fhir/search.html#Introduction

Currently, it doesn't seem that this is supported in this server implementation.

Alternatively, what other ways do I have currently to GET all resources specific to a Patient?

**Comment by eug48** [comment]
GoFHIR does support GET `/Patient/id/$everything`. It is implemented in `EverythingHandler` as `Patient?_id=%s&_include=*&_revinclude=*`

**Comment by 0xmichalis** [comment]
@eug48 thanks, $everything made the trick!
