### ISSUE TITLE
docker build issue

### ISSUE THREAD

**Issue by 0xmichalis** [eug48/fhir#5]
Trying to build from https://github.com/eug48/fhir/commit/a4169fadd6c21e719a2dd52da1d55846923e15f8
```
Step 8/13 : RUN CGO_ENABLED=0 GOOS=linux go build
 ---> Running in 6f201fc092fd
middleware/file_logger.go:15:2: build constraints exclude all Go files in /go/src/github.com/eug48/fhir/vendor/github.com/DataDog/zstd
The command '/bin/sh -c CGO_ENABLED=0 GOOS=linux go build' returned a non-zero code: 1
```

**Comment by eug48** [comment]
Apologies for the delay. I assume you were using `Dockerfile-with-mongo`? Looks like I forgot to modify it like the main `Dockerfile` when adding zstd.

**Comment by 0xmichalis** [comment]
@eug48 yeah I was using the all-in-one image. Thanks for the quick fix, works fine now!
